surname=input('Enter your surname: ')
house_number=input('Enter your house number: ')
road_name=input('Enter your road name: ')
town=input('Enter your town name: ')
print(f'Mr and Mrs {surname},\n{house_number},{road_name},\n{town}')